export const TYPES = {
    logger: Symbol('Logger'),
    app: Symbol('App'),
    usersController: Symbol('Users_Controller'),
    configService: Symbol('Config_Service'),
    prismaService: Symbol('Prisma_Service'),
    usersService: Symbol('Users_Service'),
    userRepository: Symbol('User_Repository'),
    jwtService: Symbol('Jwt_Service'),
    rolesRepository: Symbol('Roles_Repository'),
    exceptionsFilters: Symbol('Exceptions_Filters'),
    authGuardFactory: Symbol('Auth_Guard_Factory'),
    rolesService: Symbol('Roles_Service'),
    adminController: Symbol('Admin_Controller'),
    productsService: Symbol('ProductsService'),
    productsRepository: Symbol('ProductsRepository'),
    productsController: Symbol('ProductsController'),
};
