export const TYPES = {
    Logger: Symbol('Logger'),
    App: Symbol('App'),
    UsersController: Symbol('UsersController'),
    ConfigService: Symbol('ConfigService'),
    PrismaService: Symbol('PrismaService'),
    UsersService: Symbol('UsersService'),
    UserRepository: Symbol('UserRepository'),
    JWTService: Symbol('JWTService'),
    RolesOnUsersRepository: Symbol('RolesOnUsersRepository'),
    ExeptionsFilters: Symbol('ExeptionsFilters'),
    AuthGuardFactory: Symbol('AuthGuardFactory'),
    RolesService: Symbol('RolesService'),
    AdminController: Symbol('AdminController'),
};
